/** Weights, thresholds, activity profiles, and veto toggles — tune without touching logic. */

const MOON_MEAN_SPEED_DEG_PER_DAY = 13 + 10 / 60;

module.exports = {
  houseSystemElectional: "W",

  solarPhase: {
    underBeamsDeg: 15,
    combustDeg: 8.5,
    cazimiDeg: 1,
  },

  moon: {
    meanSpeedDegPerDay: MOON_MEAN_SPEED_DEG_PER_DAY,
    vocTravelDeg: 30,
    nodeProximityDeg: 12,
    aspectExactOrbDeg: 0.5,
  },

  eclipseWindowDays: 3,

  grades: [
    { min: 85, label: "Excellent" },
    { min: 70, label: "Good" },
    { min: 50, label: "Mixed" },
    { min: 30, label: "Poor" },
    { min: 0, label: "Avoid" },
  ],

  vetoes: {
    hellenisticVoidOfCourse: { enabled: true, capGrade: "Avoid" },
    moonCombust: { enabled: true, capGrade: "Avoid" },
    moonEclipseWindow: { enabled: true, capGrade: "Avoid" },
    contraryMaleficInFirst: { enabled: true, capGrade: "Avoid" },
  },

  weights: {
    moonHellVoc: -35,
    moonModernVocInfo: 0,
    moonUnderBeams: -22,
    moonCombust: -30,
    moonNewMoonDay: -18,
    moonEclipseWindow: -28,
    moonNearNode: -12,
    moonPhaseMatch: 12,
    moonPhaseMismatch: -10,
    moonFast: 5,
    moonSlow: -5,
    moonDignityDomExalt: 10,
    moonDignityDetFall: -10,
    moonApplyBenefic: 18,
    moonApplyMalefic: -18,
    moonApplyMaleficContrarySect: -8,
    moonMaltreatment: -14,
    ascRulerWellPlaced: 14,
    ascRulerBadHouse: -14,
    ascRulerUnderBeams: -10,
    ascRulerRetrograde: -10,
    ascRulerAfflicted: -12,
    beneficInFirst: 16,
    beneficInTenth: 16,
    beneficOnAngle: 8,
    maleficInFirst: -18,
    maleficInTenth: -14,
    maleficContraryFirstExtra: -10,
    maleficCadentAversion: 6,
    ascAversionToRuler: -10,
    sectBeneficStrong: 6,
    sectMaleficContrary: -8,
    dignityDomExalt: 8,
    dignityDetFall: -8,
    retrogradeKey: -8,
    underBeamsKey: -10,
    bonification: 8,
    maltreatment: -10,
    signModalityMatch: 10,
    signModalityMismatch: -8,
    activityHousePlanet: 12,
    legalAscVsSeventh: 14,
    planetaryHourMatch: 4,
    planetaryDayMatch: 3,
    natalRootingBonus: 8,
    natalRootingPenalty: -12,
    risingSignRuleReject: -55,
  },

  /** Tier weights for rankScore (must sum to 1). */
  rankWeights: {
    ascRuler: 0.4,
    moon: 0.35,
    anglesSect: 0.2,
    topic: 0.05,
  },

  rankGates: {
    minAscRulerScore: 35,
    minMoonScore: 35,
  },

  search: {
    coarseStepHours: 2,
    fineStepMinutes: 5,
    monthFineStepMinutes: 10,
    /** Ephemeris-only prescreen before full election charts (calendar month). */
    dignityPrescreen: true,
    dignityCoarseStepMinutes: 30,
    dignityFallbackMoonNeutral: true,
    maxSamplesPerDay: 144,
    scoreFloor: 35,
    rankScoreFloor: 35,
    maxWindowsMonth: 15,
    maxWindowsPerDay: 1,
    minWindowSamples: 1,
  },

  activities: {
    general: {
      id: "general",
      label: "General / unspecified",
      keyPlanets: ["moon"],
      houses: [1, 10],
      preferWaxing: true,
      signModality: null,
    },
    marriage: {
      id: "marriage",
      label: "Marriage & partnerships",
      keyPlanets: ["venus"],
      houses: [7],
      preferWaxing: true,
      signModality: "fixed",
      moonApplyTo: ["venus", "jupiter"],
    },
    contracts: {
      id: "contracts",
      label: "Contracts, business & commerce",
      keyPlanets: ["mercury"],
      houses: [2, 10],
      preferWaxing: true,
      signModality: null,
    },
    travel: {
      id: "travel",
      label: "Travel",
      keyPlanets: ["moon", "mercury"],
      houses: [3, 9],
      preferWaxing: null,
      signModality: "movable",
    },
    building: {
      id: "building",
      label: "Building, land & property",
      keyPlanets: ["saturn"],
      houses: [4],
      preferWaxing: true,
      signModality: "fixed",
      avoidMarsAfflictMoon: true,
    },
    legal: {
      id: "legal",
      label: "Legal matters & competition",
      keyPlanets: ["mars", "saturn"],
      houses: [1, 7],
      preferWaxing: true,
      signModality: null,
      compareFirstSeventhRulers: true,
    },
    medical: {
      id: "medical",
      label: "Medical treatment & health",
      keyPlanets: ["mars"],
      houses: [6],
      preferWaxing: true,
      signModality: null,
      avoidMarsAfflictMoon: true,
    },
    creative: {
      id: "creative",
      label: "Creative launch & public announcement",
      keyPlanets: ["venus", "mercury"],
      houses: [10],
      preferWaxing: true,
      signModality: null,
    },
    endings: {
      id: "endings",
      label: "Endings, releasing & removal",
      keyPlanets: ["moon", "saturn"],
      houses: [8, 12],
      preferWaxing: false,
      signModality: null,
    },
  },

  defaultActivityId: "general",
};
